# vim: set et ts=4 sw=4: -*- mode: yaml-mode; yaml-indent-offset: 4 -*-
base_url: https://gerrit.wikimedia.org/r/
bundles:
    base:
        - extensions/Cite
        - extensions/CiteThisPage
        - extensions/CodeEditor
        - extensions/ConfirmEdit
        - extensions/Gadgets
        - extensions/ImageMap
        - extensions/InputBox
        - extensions/Interwiki
        - extensions/LocalisationUpdate
        - extensions/Nuke
        - extensions/OATHAuth
        - extensions/ParserFunctions
        - extensions/PdfHandler
        - extensions/Poem
        - extensions/Renameuser
        - extensions/SpamBlacklist
        - extensions/SyntaxHighlight_GeSHi
        - extensions/TitleBlacklist
        - extensions/WikiEditor
        - skins/MonoBook
        - skins/Vector
manual_branch_points:
    REL1_27:
        core: 0cd28e19cb0f9385a2a1cc11a4d8c9c21ff0b830
    REL1_29:
        core: 0cd28e19cb0f9385a2a1cc11a4d8c9c21ff0b830
    REL1_30:
        core: 0cd28e19cb0f9385a2a1cc11a4d8c9c21ff0b830
sub_submodules:
    extensions/VisualEditor: lib/ve
diff:
    ignore:
        - "*~"
        - ".js*"
        - ".git*"
        - "#*#"
        - ".#*"
        - ".rubocop*"
        - .travis.yml
        - package.json
        - messages
        - "Gemfile*"
        - ".mailmap"
        - "*.png"
        - "*.jpg"
        - "*.xcf"
        - "*.gif"
        - "*.svg"
        - "*.tiff"
        - "*.zip"
        - "*.xmp"
tar:
    ignore:
        - "*~"
        - "#*#"
        - ".*"
        - package.json
        - README.mediawiki
        - "Gemfile*"
        - "vendor/pear/net_smtp/README.rst"
